### ISSUE TITLE
Fix the `[pub]` hack in `prop_compose!`

### ISSUE THREAD

**Issue by boustrophedon** [AltSysrq/proptest#97] opened 2018-10-25 23:39 UTC
[As of 1.30](https://blog.rust-lang.org/2018/10/25/Rust-1.30.0.html) it seems that you can now match on visibility keywords. Does this enable us to get rid of the `[pub]` hack in the `prop_compose!` macro? I haven't played with advanced macros so I'm not sure if it actually solves the problem. Also, it would make using the crate itself require a rustc >= 1.30.

**Comment by AltSysrq** [comment] 2018-10-25 23:53
Duplicate of https://github.com/AltSysrq/proptest/issues/10

Thanks for pointing out that it's now stable though, that had fallen off my radar. I'll see about adding support for the new matcher next time there's a release with breaking changes.

**Comment by Centril** [comment] 2018-10-26 00:14
I'd recommend lumping in this change with the stabilization of the `?` macro matcher (https://github.com/rust-lang/rust/issues/48075#issuecomment-433177613) at least as well as a change to edition 2018. This should make the macros somewhat simpler.

We might also want to consider experimenting with attribute proc macros now that they are stable, for example:

```rust
#[proptest]
fn foo(x: u8, ...) { .. }
```

tho it is unclear what to do about the `x in strategy` syntax as it would likely result in a parse error before attr proc macro expansion gets to run.

**Comment by AltSysrq** [comment] 2019-02-04 05:47
At long last, this issue is fixed in 0.9.0. Unfortunately I wasn't able to preserve the old way of doing things, so when you upgrade you will _need_ to remove the brackets around the visibility modifier.

**Closed by AltSysrq** 2019-02-04 05:47 UTC
Labels: breaking-changes, duplicate, enhancement, v-0.9.0
