### ISSUE TITLE
Panic for proptest::sample::subsequence(vec![], 0..0)

### ISSUE THREAD

**Issue by rawler** [AltSysrq/proptest#87] opened 2018-08-26 17:04 UTC
The most reduced test-case for my example, is the empty vector.

Given the empty vector (and asked for zero samples), proptest panics with 

> ... panicked 'attempt to subtract with overflow', .cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.8.5/src/collection.rs:111:61

**Comment by rawler** [comment] 2018-08-26 17:11
Minimal example:

    proptest! {
        #[test]
        fn reproduction(input in (1..33usize).prop_flat_map(|size| (Just(size), prop::sample::subsequence((1..size).collect::<Vec<usize>>(), 0..size-1).boxed()))) {
            panic!("Nope {:?}", input);
        }
    }

Output:

    ---- reproduction stdout ----
    thread 'reproduction' panicked at 'Nope (13, [3, 4, 5, 10, 11])', src/test.rs:670:13
    note: Run with `RUST_BACKTRACE=1` for a backtrace.
    thread 'reproduction' panicked at 'Nope (13, [4, 5, 10, 11])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (13, [5, 10, 11])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (13, [10, 11])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (13, [11])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (13, [])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (7, [1, 2, 4, 5, 6])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (7, [2, 4, 5, 6])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (7, [4, 5, 6])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (7, [5, 6])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (7, [6])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (7, [])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (4, [1, 3])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (4, [3])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (4, [])', src/test.rs:670:13
    thread 'reproduction' panicked at 'Nope (2, [])', src/test.rs:670:13
    thread 'reproduction' panicked at 'attempt to subtract with overflow', .cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.8.5/src/collection.rs:111:61

**Comment by Centril** [comment] 2018-08-26 17:28
Some discussion on this in: https://github.com/AltSysrq/proptest/issues/85#issuecomment-415779809.

**Comment by AltSysrq** [comment] 2018-08-26 17:31
`sample(input, 0..0)` can't do anything _but_ panic because the size range is empty, i.e., there are no sizes at all that it would be allowed to generate

**Comment by rawler** [comment] 2018-08-26 17:33
@AltSysrq But of course! My bad, sorry.

**Comment by rawler** [comment] 2018-08-26 17:49
So, after some experiments; How WOULD I go about generating a [potentially 0-length] set of samples from a [potentially 0-length] collection?

`sample(vec![], 0..1)` does not seem legal either? (Despite the only valid value for output-size is now exactly 0 elements)

Right now I completely side-step `subsequence` for the special-case of input being empty, but that does not seem right.

In particular, I ponder the error: 

> Illegal SampledBitSetStrategy: have 12 bits available, but requested size is 0..13

So, the maximum possible requested size is exactly 12. Is this really an error?

**Comment by AltSysrq** [comment] 2018-08-26 17:51
There might be something going on there. I'm looking at other stuff involving size ranges in a bit anyway, maybe they have the same root cause.

**Comment by AltSysrq** [comment] 2018-08-27 00:44
There were a couple off-by-one errors. They have been fixed in 0.8.6. 0.8.6 also has an explicit check for things like `0..0` so the problem is more obvious.

**Closed by AltSysrq** 2018-08-27 00:44 UTC
